name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: cargo run --help
      run: cargo run -- --help
    - name: query ero_sagiri uuid
      run: cargo run ero_sagiri
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: query_minecraft_uuid
        path: ${{ github.workspace }}/target/debug/query_minecraft_uuid
